version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 861276092440.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=861276092440.dkr.ecr.us-east-1.amazonaws.com/chat_caristeo:latest
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating ECS Service with new image
      - aws ecs update-service --cluster chat_caristeo_cluster --service chat_caristeo_service01 --force-new-deployment

AKIA4RCAOHAMJJ3VEJUZ

ZpbNIDGToBRs2H4NZsReqwVm4FYJfvJxmHzJsMCD